---
title: "YES Monitoring and Evaluation Framework"
orientation: rows
output:
  flexdashboard::flex_dashboard: null
  theme: cosmo
resource_files:
- prov_summary/global.R
- prov_summary/server.R
- prov_summary/styles.css
- prov_summary/ui.R
- youth_page/server.R
- youth_page/ui.R
- data/processed/placed_youth_unique.csv
- data/processed/weekly_cleaned.csv
- SA_shp/ZA_province.shx
- SA_shp/ZA_province.qpj
- SA_shp/ZA_province.cpg
- SA_shp/ZA_province.prj
- SA_shp/ZA_province_centroid.prj
- SA_shp/ZA_province_centroid.qpj
- SA_shp/ZA_province_centroid.shx
runtime: shiny
logo: images/logo_tiny.png
vertical_layout: scroll
---



  
```{r setup, include=FALSE}
## Inside the working directory create a sampleID folder to contain information of the sampleID's
## they should be named according to the sampleID names
library(tidyverse)
library(lubridate)
library(shinydashboard)
library(plotly)
library(maptools)
#_________________________________________________________________
#lib <- c("dplyr","ggplot2","ggpubr","" ,"tidyr" ,"" ,"")
#lapply(lib, library, character.only = TRUE)

##_creating a negatiing function____###

"%ni%" <- Negate("%in%")
#### save all the files as objects
#Increasing the default maximum upload restriction of Shiny to 10GB can add to globaly
if(Sys.getenv('SHINY_PORT') == "") options(shiny.maxRequestSize=10000*1024^2)
```


Country Overview {data-width=8000}
======

```{r}
fluidRow(
    column(12,div(style = "height:1000px;background-color: white;margin: 0;padding: 0;",
                  shinyAppDir("prov_summary",
            options = list(width = "100%", height = "100%"))
)))
```



Company Overview {data-width=300}
======



Youth dashboard {data-width=8000}
======
```{r}
fluidRow(
    column(12,div(style = "height:1000px;background-color: white;margin: 0;padding: 0;",
shinyAppDir("youth_page",
            options = list(width = "100%", height = "100%"))
)))
```


